### PR TITLE
Remove isReferenceData and ITEMGROUPDATASEQ

### PR DESCRIPTION
**Pull request by lexjansen**
Updated schemas and all .json and .ndjson examples.

### CODE REVIEW

**Comment by swhume** [comment]
Updates look good

**Review by swhume — APPROVED** [review]
dataset and schema updates look good

**Comment by swhume** [comment]
@DmitryMK I'm going to merge this so we meet our GGG deadlines. If you find something we need to fix please submit another PR. Thx.

**Comment by DmitryMK** [comment]
I have also validated everything against the schema. And I agree those questions can be discussed outside of this update, so it is good to merge.

**Pull request merged**
